port=53
no-hosts
log-queries
log-facility=/var/log/dnsmasq.log

domain-needed
bogus-priv

domain=team1.test
local=/team1.test/

address=/app.team1.test/192.168.1.50
address=/api.team1.test/192.168.1.50
